# POST  http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname" :"John",
#     "email": "joh1n@gmail.com",
#     "password":"John@123"
#  }

# POST http://localhost:3000/get-blogs
# Content-Type: application/json

# {
#   "blog_id":"ReactJs-A-part-of-Programming-oAf9u6gBIZQaTQLDP26ru"
# }

POST http://localhost:3000/get-profile
Content-Type: application/json

{
  "username":"priyanshawasthi09"
}
