# POST  http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname" :"John",
#     "email": "joh1n@gmail.com",
#     "password":"John@123"
#  }

GET http://localhost:3000/latest-blogs
